---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Remove image
      docker_image:
        name: vishalgovil/miniprojspe
        state: absent
        force: yes
    - name: Pull new image
      docker_image:
        name: vishalgovil/miniprojspe
